[[redirects]]
  from = "/kit-luna-system-cristalli"
  to = "/search"
  status = 301

[[redirects]]
  from = "/luna-plex-amino-150ml"
  to = "/search"
  status = 301

[[redirects]]
  from = "/kit-luna-elixir-shampoo-mascara-leave-in"
  to = "/search"
  status = 301

[[redirects]]
  from = "/reconstrutor-da-luna-system-500g"
  to = "/search"
  status = 301

[[redirects]]
  from = "/kit-luna-relax-shampoo-e-hidroxico-de-sodio"
  to = "/search"
  status = 301

[[redirects]]
  from = "/kit-luna-elixir-shampoo-mascara-leave-in"
  to = "/search"
  status = 301

[[redirects]]
  from = "/grid/*"
  to = "/search"
  status = 301

[[redirects]]
  from = "/content/*"
  to = "/search"
  status = 301

[[redirects]]
  from = "/marca/*"
  to = "/search"
  status = 301

[[redirects]]
  from = "/contate-nos"
  to = "/search"
  status = 301

[[redirects]]
  from = "/pagina/*"
  to = "/search"
  status = 301

[build]
  publish = "publish"
  functions = "functions-zip"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr?slug=:splat"
  status = 200

[[headers]]
  for = "/storefront.*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/storefront.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/storefront.css"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/checkout.*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/checkout.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/chunk.*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=60, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, s-maxage=600"
